# Generated by Django 4.2.4 on 2023-08-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questgen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='store'),
        ),
    ]
