# Generated by Django 4.2.4 on 2023-08-08 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questgen", "0002_filemodel_text_alter_filemodel_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="filemodel",
            name="easy",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="filemodel",
            name="hard",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="filemodel",
            name="medium",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="filemodel",
            name="type",
            field=models.IntegerField(default=0),
        ),
    ]
